### ISSUE TITLE
Update count action

### ISSUE THREAD

**Issue by scorcism** [asPerReqirements/click-counter#4]
As you start playing the game,
when the counts are multiple of 30, we get a cookie to click.

when we click on the cookie our score increases by +10  

It will be great if the count doubles everytime 
for 1st time +10 ,
for 2nd time  +20,
for 3rd time +30 

....

**Comment by Vayras** [comment]
Hi @scorcism I would Like to work on this issue can you please assign me this.

**Comment by scorcism** [comment]
@Vayras yes go for it

**Comment by Vayras** [comment]
@scorcism i have created a pull request can you please check it , also let me know if there are any issues

**Comment by scorcism** [comment]
@Vayras Everything was perfect.

You can create more issues for any further updates

**Comment by Vayras** [comment]
@scorcism Absolutely, that sounds great! Looking forward to collaborating
